apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-hackaton-be-db
  labels:
    app: quarkus-hackaton-be-db
data:
  POSTGRES_DB: quarkus-hackaton
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres