apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-hackaton-be-db
  labels:
    app: quarkus-hackaton-be-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-hackaton-be-db
  template:
    metadata:
      labels:
        app: quarkus-hackaton-be-db
    spec:
      containers:
        - name: quarkus-hackaton-be-db
          image: debezium/postgres:12-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: quarkus-hackaton-be-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim