version: '3.8'

services:
  quarkus-hackaton-ai-app:
    container_name: quarkus-hackaton-ai-app
    image: quarkus-hackaton-ai-app
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8082:8082"

networks:
  default:
    external:
      name: quarkus-hackaton-network