version: '3.8'

services:
  quarkus-hackaton-kafka:
    container_name: quarkus-hackaton-kafka
    image: landoop/fast-data-dev:2.5
    environment:
      ADV_HOST: 127.0.0.1                       # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                               # Disable Running tests so the cluster starts faster
      CONNECTORS: debezium-postgres             # Allows only described connectors
      SAMPLEDATA: 0                             # Disable sample data topic creation
      RUNNING_SAMPLEDATA: 0                     # Disable sample data
    ports:
      - 2181:2181                               # Zookeeper
      - 3030:3030                               # Landoop UI
      - 8091-8093:8081-8083                     # REST Proxy, Schema Registry, & Kafka Connect
      - 9581-9585:9581-9585                     # JMX Ports
      - 9092:9092                               # Kafka Broker

  quarkus-hackaton-prometheus:
    container_name: quarkus-hackaton-prometheus
    image: prom/prometheus:v2.15.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

networks:
  default:
    external:
      name: quarkus-hackaton-network