version: '3.8'

services:
  quarkus-hackaton-ui-app:
    container_name: quarkus-hackaton-ui-app
    image: quarkus/quarkus-hackaton-ui
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: quarkus-hackaton-network